services:
  postgres:
    image: ${POSTGRES_IMAGE:-postgres:16}
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-mcp_gateway}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    image: ${WEB_IMAGE:-ghcr.io/mcp-ecosystem/mcp-gateway/web:latest}
    ports:
      - "80:80"
    depends_on:
      - apiserver
      - mcp-gateway
      - mock-user-svc
    restart: unless-stopped

  apiserver:
    image: ${APISERVER_IMAGE:-ghcr.io/mcp-ecosystem/mcp-gateway/apiserver:latest}
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    volumes:
      - ./configs:/app/configs
      - ./data:/app/data
      - ./.env.multi:/app/.env
    depends_on:
      - postgres
    restart: unless-stopped

  mcp-gateway:
    image: ${MCP_GATEWAY_IMAGE:-ghcr.io/mcp-ecosystem/mcp-gateway/mcp-gateway:latest}
    ports:
      - "8081:8081"
    environment:
      - ENV=production
    volumes:
      - ./configs:/app/configs
      - ./data:/app/data
      - ./.env.multi:/app/.env
    depends_on:
      - postgres
    restart: unless-stopped

  mock-user-svc:
    image: ${MOCK_USER_SVC_IMAGE:-ghcr.io/mcp-ecosystem/mcp-gateway/mock-user-svc:latest}
    ports:
      - "8082:8082"
    environment:
      - ENV=production
    volumes:
      - ./configs:/app/configs
      - ./data:/app/data
      - ./.env.multi:/app/.env
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
