version: '3.8'

services:
  nginx:
    image: ${NGINX_IMAGE:-nginx:1.27.5-bookworm}
    ports:
      - "80:80"
    volumes:
      - ./deploy/docker/multi/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/dist:/usr/share/nginx/html:ro
    depends_on:
      - apiserver
      - mcp-gateway
      - mock-user-svc
    restart: unless-stopped

  apiserver:
    image: ${REGISTRY:-docker.io}/${PROJECT_NAME:-mcp-gateway}/apiserver:${VERSION:-latest}
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    volumes:
      - ./configs:/app/configs
      - ./data:/app/data
    restart: unless-stopped

  mcp-gateway:
    image: ${REGISTRY:-docker.io}/${PROJECT_NAME:-mcp-gateway}/mcp-gateway:${VERSION:-latest}
    ports:
      - "8081:8081"
    environment:
      - ENV=production
    volumes:
      - ./configs:/app/configs
      - ./data:/app/data
    restart: unless-stopped

  mock-user-svc:
    image: ${REGISTRY:-docker.io}/${PROJECT_NAME:-mcp-gateway}/mock-user-svc:${VERSION:-latest}
    ports:
      - "8082:8082"
    environment:
      - ENV=production
    volumes:
      - ./configs:/app/configs
      - ./data:/app/data
    restart: unless-stopped
