apiVersion: v1
kind: Service
metadata:
  name: mcp-gateway
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - name: {{ $value.name }}
      port: {{ $value.port }}
      targetPort: {{ $value.port }}
  {{- end }}
  selector:
    app: mcp-gateway