apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: unla
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          imagePullPolicy: IfNotPresent
          # image: ghcr.io/amoylab/unla/web:latest
          image: registry.ap-southeast-1.aliyuncs.com/amoylab/unla-web:latest
          env:
            - name: TZ
              value: UTC
            - name: ENV
              value: production
          envFrom:
            - configMapRef:
                name: unla-env
          ports:
            - containerPort: 80
            - containerPort: 5234
