apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: unla
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      name: my-web
    - port: 5234
      targetPort: 5234
      nodePort: 30234
      name: my-web-api
  selector:
    app: web
