database:
  type: postgres
  host: "${DB_HOST:localhost}"
  port: ${DB_PORT:5432}
  user: "${DB_USER:postgres}"
  password: "${DB_PASSWORD:example}"
  dbname: "${DB_NAME:mcp-gateway}"
  sslmode: "${DB_SSL_MODE:disable}"

openai:
  api_key: "${OPENAI_API_KEY}"
  model: "${OPENAI_MODEL:gpt-4.1}"
