database:
  type: "${APISERVER_DB_TYPE:sqlite}"
  host: "${APISERVER_DB_HOST:localhost}"
  port: ${APISERVER_DB_PORT:5432}
  user: "${APISERVER_DB_USER:postgres}"
  password: "${APISERVER_DB_PASSWORD:example}"
  dbname: "${APISERVER_DB_NAME:./mcp-gateway.db}"
  sslmode: "${APISERVER_DB_SSL_MODE:disable}"

# Storage configuration
storage:
  type: "${GATEWAY_STORAGE_TYPE:db}"  # disk or db
  # Database configuration (only used when type is db)
  database:
    type: "${GATEWAY_DB_TYPE:sqlite}"
    host: "${GATEWAY_DB_HOST:localhost}"
    port: ${GATEWAY_DB_PORT:5432}
    user: "${GATEWAY_DB_USER:postgres}"
    password: "${GATEWAY_DB_PASSWORD:example}"
    dbname: "${GATEWAY_DB_NAME:./data/mcp-gateway.db}"
    sslmode: "${GATEWAY_DB_SSL_MODE:disable}"
  # Disk configuration (only used when type is disk)
  disk:
    path: "${GATEWAY_STORAGE_DISK_PATH:}"

# Notifier configuration
notifier:
  role: "${APISERVER_NOTIFIER_ROLE:sender}"
  # Type of notifier to use (signal, api, redis, composite)
  type: "${APISERVER_NOTIFIER_TYPE:signal}"

  # Signal configuration (only used when type is signal)
  signal:
    signal: "${APISERVER_NOTIFIER_SIGNAL:SIGHUP}"
    pid: "${APISERVER_NOTIFIER_SIGNAL_PID:/var/run/mcp-gateway.pid}"

  # API configuration (only used when type is api)
  api:
    port: ${APISERVER_NOTIFIER_API_PORT:5235}
    target_url: "${APISERVER_NOTIFIER_API_TARGET_URL:http://localhost:5235/_reload}"

  # Redis configuration (only used when type is redis)
  redis:
    addr: "${APISERVER_NOTIFIER_REDIS_ADDR:localhost:6379}"
    password: "${APISERVER_NOTIFIER_REDIS_PASSWORD:UseStrongPasswordIsAGoodPractice}"
    db: ${APISERVER_NOTIFIER_REDIS_DB:0}
    topic: "${APISERVER_NOTIFIER_REDIS_TOPIC:mcp-gateway:reload}"

openai:
  api_key: "${OPENAI_API_KEY}"
  model: "${OPENAI_MODEL:gpt-4.1}"
  base_url: "${OPENAI_BASE_URL:https://api.openai.com/v1/}"
