database:
  type: postgres
  host: "${DB_HOST:localhost}"
  port: ${DB_PORT:5432}
  user: "${DB_USER:postgres}"
  password: "${DB_PASSWORD:example}"
  dbname: "${DB_NAME:mcp-gateway}"
  sslmode: "${DB_SSL_MODE:disable}"
