services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-mcp_gateway}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mcp-gateway:
    image: ${IMAGE:-ghcr.io/mcp-ecosystem/mcp-gateway/allinone:latest}
    ports:
      - "80:80"
      - "5234:5234"
      - "5235:5235"
      - "5236:5236"
    environment:
      - ENV=production
      - VITE_MCP_SERVER_URL=${VITE_MCP_SERVER_URL}
    volumes:
      - ./configs:/app/configs
      - ./data:/app/data
      - ./.env.allinone:/app/.env
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
